config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'products#index'
  # get "/products/new" => "products#new", as: :new_product
  # post "/products" => "products#create", as: :products
  # get "/products/:id" => "products#show", as: :product 
  # get "/products" => "products#index"
  # delete "/products/:id" => "products#destroy"
  # get "/products/:id/edit" => "products#edit", as: :edit_product
  # patch "/products/:id" => "products#update"
  patch "/reviews/:id/toggle" => "reviews#toggle_hidden", as: "toggle_hidden"
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :products do
    # creates the following route for us:
    # post('/products/:product_id/reviews, { to: 'reviews#create', as: :product_reviews })
    # which, due to the 'as' creates a method called 'product_reviews_path' 
    # This method requires one variable, a product or product id to 'fill in'
    # the value for ':product_id', in the path it returns 
    # the value: '/products/:product_id/reviews' with the :product_id 
    # "filled in"
    # Shallow: https://api.rubyonrails.org/classes/ActionDispatch/Routing/Mapper/Resources.html#method-i-resources
    resources :reviews, shallow: true,  only: [:create, :destroy] do 
      resources :likes, only: [:create, :destroy]
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
    before_validation :set_defaults
    before_save :capitalize_title

    has_many(:reviews, dependent: :destroy)
    belongs_to :user 

    validates :title, {
        presence: true, 
        uniqueness: { case_sensitive: false}
    }

    validates :price, {
        numericality: { greater_than_or_equal_to: 0}
    }
    
    validates :description, {
        presence: true, 
        length: { minimum: 10}
    }

    private 

    def set_defaults
        self.price ||= 1
    end

    def capitalize_title 
        self.title = self.title.capitalize 
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_product, only: [:show, :edit, :update, :destroy]

    def new 
        @product = Product.new
    end

    def create 
        @product = Product.new product_params
        @product.user = @current_user
        if @product.save
            redirect_to @product
        else
            render :new 
        end
    end

    def edit 
    end

    def update 
        if @product.update product_params
            redirect_to product_path(@product)
        else 
            render :edit 
        end
    end

    def show 
        @review = Review.new 
        # In this case only the product owner will have all reviews available in the 
        # through @reviews (including hidden reviews).
        # You ccould also remove this logic here and do some logic in the view. Your
        # use case (and for now, the size of  your Rails toolset) will determine the best way
        # to things. We've done it this way because with the tools available to us 
        # it minimizes the amount of repeated code an d if else statements in our view. 
        if can? :manage, @product 
            @reviews = @product.reviews.order(created_at: :desc)
        else
            @reviews = @product.reviews.where(hidden: false).order(created_at: :desc)
        end 
    end

    def index 
        @products = Product.order(created_at: :DESC)
    end

    def destroy 
        @product.destroy 
        redirect_to products_path
    end

    private 

    def product_params
        params.require(:product).permit(:title, :description, :price)
    end

    def find_product 
        @product = Product.find params[:id]
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<% if @product.errors.any? %>
    <ul>
        <% @product.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for @product do |f| %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :price %>
        <%= f.number_field :price, class: "form-control" %>
    </div>
    <%= f.submit 'Submit', class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<h1>All Products</h1>
<% @products.each do |product| %>
    <ul class="list-group">
        <li class="list-group-item"><%= link_to product.title, product_path(product) %></li>
    </ul>
<% end %>

app/views/products/new.html.erb
<h1>Add a new product</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= @product.title %></h5>
    <p class="text-primary">Price: <%= number_to_currency(@product.price, precision: 2) %></p>
    <p class="card-text">Description: <%= @product.description %></p>
    <small>User: <%= @product.user.full_name %></small>
    <% if can? :edit, @product %>
        <%= link_to "Edit Product", edit_product_path(@product), class: "btn btn-primary" %>
    <% end %>

    <% if can? :destroy, @product %>
        <%= link_to 'Delete Product', 
            product_path(@product), 
            class: "btn btn-danger",
            method: :delete, 
            data: { confirm: 'Are you sure that you want to delete this product? '} 
        %>
    <% end %>
  </div>
</div>



<%# 
    New Review Form 

    'form_for [@product, @review]' require there to be a method called 
    'product_reviews_path' defined in routes. Using the 'resources' method in 
    routes, this gets defined for us (see config/routes)

    @review is an empty reveiw (Review.new) defined in 'products#show'
 %>
<hr />
<h3>Leave a Review</h3>
<%= form_for [@product, @review] do |f| %>
    <% if @review.errors.present? %>
        <p>
            <%= @review.errors.full_messages.join(', ') %>
        </p>
    <% end %>

    <div class="form-group">
        <%= f.label :rating %>
        <%= f.number_field :rating, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: "form-control" %>
    </div>
    <%= f.submit 'Leave a Review', class: 'btn btn-primary' %>
<% end %>

<hr />
<h3>Reviews</h3>
<%#
    Display all of the reviews for this product
%>

<ul class="list-group">
    <% @reviews.each do |review| %>
            <div class="<%= 'hidden-review' if review.hidden %>">
                <li class="list-group-item">
                <h3>Rating: <%= review.rating %></h3>
                <p><%= review.body %></p>
                <p>User: <%= review.user.full_name %></p>
                <% if can? :manage, review %>
                <%= link_to 'Delete',
                    review_path(review),
                    class: "btn btn-danger brn-sm",
                    method: :delete, 
                    data: {
                        confirm: 'Are you sure that you want to delete this review?'
                    }
                %>
                <% end %>
                
                <%= link_to "#{review.hidden ? 'Show' : 'Hide' }", toggle_hidden_path(review), method: :patch %>
                <% if user_signed_in?  && current_user != review.user %>
                    <% like = current_user.likes.find_by_review_id(review) %>
                    <% if like %>
                        <%= link_to 'Unlink', like_path(like), method: :delete %>
                    <% else %>
                        <%= link_to 'Like', review_likes_path(review), method: :post %>
                    <% end %>
                <% end %>
                (<%= pluralize review.likes.count, 'like'%>)
                </li>
            </div>
    <% end %>
</ul>