config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'products#index'
  # get "/products/new" => "products#new", as: :new_product
  # post "/products" => "products#create", as: :products
  # get "/products/:id" => "products#show", as: :product 
  # get "/products" => "products#index"
  # delete "/products/:id" => "products#destroy"
  # get "/products/:id/edit" => "products#edit", as: :edit_product
  # patch "/products/:id" => "products#update"
  patch "/reviews/:id/toggle" => "reviews#toggle_hidden", as: "toggle_hidden"
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :products do
    # creates the following route for us:
    # post('/products/:product_id/reviews, { to: 'reviews#create', as: :product_reviews })
    # which, due to the 'as' creates a method called 'product_reviews_path' 
    # This method requires one variable, a product or product id to 'fill in'
    # the value for ':product_id', in the path it returns 
    # the value: '/products/:product_id/reviews' with the :product_id 
    # "filled in"
    # Shallow: https://api.rubyonrails.org/classes/ActionDispatch/Routing/Mapper/Resources.html#method-i-resources
    resources :reviews, shallow: true,  only: [:create, :destroy] do 
      resources :likes, only: [:create, :destroy]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmazonProducts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" />
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Amazon Products</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <%= link_to 'Home', root_path, class: "nav-item nav-link" %>
          <%= link_to 'New Product', new_product_path, class: "nav-item nav-link" %>
          <%= link_to 'All Products', products_path, class: "nav-item nav-link" %>
        </ul>
        <% if user_signed_in? %>
          <a class="nav-item nav-link">Hello <%= current_user.first_name %><a>
          <%= link_to 'Sign Out', session_path, method: :delete, class: 'nav-item nav-link'%>
        <% else %>
          <%= link_to 'Sign In', new_session_path, class: 'btn btn-outline-success my-2 my-sm-0'%>
          <%= link_to 'Sign Up', new_user_path, class: 'btn btn-outline-success my-2 my-sm-0'%>
        <% end %>
      </div>
    </nav>
    <div class="container-fluid">
      <% if flash[:notice].present? || flash[:alert].present? %>
        <div class="flash-message">
          <%= flash[:notice] || flash[:alert] %>
        </div>
        <% end %>
      <%= yield %>
    </div>
  </body>
</html>